### ISSUE TITLE
Make Backend Routes for Published Schedule

### ISSUE THREAD

**Issue by ThatMegamind** [ctc-uci/aiss-backend#19]
## Instructions
- Modify the primary `GET` query to also retrieve the title and host for each event in the Published Schedule by using `LEFT JOIN`
- Create CRUD routes for each query associated with `Published Schedule`, which will allow us to access the data from the frontend

## Notes
- Use the queries under `server/queries/published_schedule.sql` as a jumping-off point!

### Routes should be created for the following:
- `GET` - Returns all data from the published_schedule table
- `GET/:id` - returns the rows that match the given id
- `POST` - Adds a new row to the published_schedule table
- `PUT/:id` - Updates an existing row given an id
- `DELETE/:id` - deletes an existing row given an id

### Logistics:
- Add the routes in a file located in `routes/publishedSchedule.js`
- `app.js` should be updated accordingly
- Delete `server/queries/published_schedule.sql` once this task is complete

## Resources
- [2.3: Backend Programming](https://docs.google.com/document/d/1S6hJdZJ-dbRTRIdnqGDSzbO5d5nv95D8hrwJDIoMb6c/edit#heading=h.ss1h6pz82xhv)
- [DB Model](https://www.figma.com/file/NDPdo1MR13qgsB4LubtzyZ/Database-Model?type=whiteboard&node-id=0-1&t=m1J0vcLI2mzIb5SN-0)

#### As always, feel free to message Michael _and_ Michelle if you have any questions!

**Comment by seancfong** [comment]
`Modify the primary GET query to also retrieve the title and host for each event in the Published Schedule by using LEFT JOIN`

Should the `GET/:id` route remain unchanged?

**Comment by ThatMegamind** [comment]
> `Modify the primary GET query to also retrieve the title and host for each event in the Published Schedule by using LEFT JOIN`
> 
> Should the `GET/:id` route remain unchanged?

Thanks for catching that! Both should be updated in the same way
