### ISSUE TITLE
Add Event to Published Schedule (Backend) 

### ISSUE THREAD

**Issue by michellelin1** [ctc-uci/aiss-backend#46]
## Instructions
- To support grouping events by day, we need to add a new table `Day` that will store information that is the same across events in the day.
- The idea is that this will reduce data redundancy and make queries simpler and faster.
- Add the new `day` table in Postgres and modify the `published_schedule` table add the foreign key
  - The start_time and end_time types have also changed from TIMESTAMP to TIME 
- Update the `POST  /published-schedule` route to support the new day id
- Add a new route `POST /published-schedule/add-day` to add a new row in the day table
 
## Notes
- It might be easier to drop the `published_schedule` instead of modifying it
 
## Resources
- [DB Model](https://www.figma.com/file/NDPdo1MR13qgsB4LubtzyZ/Database-Model?type=whiteboard&node-id=0-1&t=CLDsAYOiY7Irhg62-0)

**Comment by ThatMegamind** [comment]
## New Instructions
- In the last sprint, the modals have been set up for the published schedule to add new events or edit them. However the actual functionality of adding/editing events to the published schedule has not been implemented yet. 
- For this task you will need to finish adding events to the published schedule and enable users to modify existing events in the catalog.

## Notes
- There is preexisting hover functionality of the table rows that you can use for the edit events done by Kade and Lianne.
- The main difference between what they did, is that it opens a form specific for the catalog events.. In this sprint the hover functionality of the catalog while in the day planner modal needs to open a pre-populated form (same component as the “new add event” form).

## Acceptance Criteria
- Check that the events are added to both the published schedule and catalog (for both new events using the add button and events pre-existing from the catalog)
Within Planner Layout modal:
    - Submission of the create new event form keeps user in Planner Layout modal
