### ISSUE TITLE
Bug Batch 2 (Backend)

### ISSUE THREAD

**Issue by michellelin1** [ctc-uci/aiss-backend#58]
## Instructions
- Since the Published Schedule table and Catalog table are linked together, we’ve realized that if someone made modifications to an event in the Catalog table, those changes would unintentionally be reflected in events in the Published Schedule table (and we don’t want that since the schedule is supposed to be final). Additionally, you wouldn’t be able to delete a Catalog Event if it was referenced in a Published Schedule row.
- As a result we decided to
  - Remove the edit button from the Catalog table (comment out the code incase we still want it)
  - Add a new row to Catalog table in the backend to called “hidden”
     - Hidden should be defaulted to false in `POST /catalog`
     - In `GET /catalog`, only return rows that are not hidden
     - In `DELETE /catalog`, if event_id is not referenced at all in the Published Schedule table, delete it like normal. Otherwise, set hidden to true.
- Additionally, we would like you to modify the foreign key references to day_id in the published_schedule table to delete on cascade.

## Acceptance Criteria
- The edit button is no longer apparent in the catalog table
- Users can “delete” rows from the Catalog 
- When you delete a day object, all Published Schedule events associated with it are also deleted.

## Resources
- [ON DELETE CASCADE](https://www.ibm.com/docs/en/informix-servers/14.10?topic=clause-using-delete-cascade-option)

**Comment by h0ethan04** [comment]
### Additional Acceptance Criteria:
- Forbidden from adding duplicate days to the day table
